### PR TITLE
use proper build prop

### PR DESCRIPTION
**Pull request by tmthang86**

### CODE REVIEW

**Comment by luk1337** [comment]
Change the commit message to something like "a9xprolte: Use proper device properties"

**Comment by luk1337** [comment]
don't open a new pr, amend the current commit.

**Comment by tmthang86** [comment]
a9xprolte: Use proper device properties

**Comment by luk1337** [comment]
I wanted you to amend commit message not pull request description.

**Comment by tmthang86** [comment]
changed

**Pull request merged**
